
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// It is automatically generated by Next.js

declare namespace NodeJS {
  interface ProcessEnv {
    readonly NODE_ENV: 'development' | 'production' | 'test';
    readonly PUBLIC_URL: string;
  }
}
